all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/matthieu/UbuntuData/VScode/devops-livecoding/ansible/inventories/id_rsa
  children:
    prod:
      hosts:
        matthieu.freire.eleuterio.takima.cloud:
